#############################################################################
# Makefile for building: JimberAtomicSwap
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  atomicSwap.pro
# Template: app
# Command: /home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/qmake -o Makefile atomicSwap.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../include -I../include/QtQuickControls2 -I../include/QtQuick -I../include/QtWidgets -I../include/QtGui -I../include/QtQml -I../include/QtNetwork -I../include/QtCore -I. -isystem /usr/include/libdrm -I../mkspecs/linux-g++
QMAKE         = /home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = JimberAtomicSwap1.0.0
DISTDIR = /home/kristof/Qt5.10.0/5.10.0/gcc_64/atomicSwap/.tmp/JimberAtomicSwap1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/kristof/Qt5.10.0/5.10.0/gcc_64/lib -Wl,-rpath-link,/home/kristof/Qt5.10.0/5.10.0/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/kristof/Qt5.10.0/5.10.0/gcc_64/lib -lQt5QuickControls2 -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = atomicSwap.cpp \
		backend.cpp \
		documenthandler.cpp \
		mustache.cpp qrc_atomicSwap.cpp \
		moc_backend.cpp \
		moc_documenthandler.cpp
OBJECTS       = atomicSwap.o \
		backend.o \
		documenthandler.o \
		mustache.o \
		qrc_atomicSwap.o \
		moc_backend.o \
		moc_documenthandler.o
DIST          = ../mkspecs/features/spec_pre.prf \
		../mkspecs/common/unix.conf \
		../mkspecs/common/linux.conf \
		../mkspecs/common/sanitize.conf \
		../mkspecs/common/gcc-base.conf \
		../mkspecs/common/gcc-base-unix.conf \
		../mkspecs/common/g++-base.conf \
		../mkspecs/common/g++-unix.conf \
		../mkspecs/qconfig.pri \
		../mkspecs/modules/qt_lib_3danimation.pri \
		../mkspecs/modules/qt_lib_3danimation_private.pri \
		../mkspecs/modules/qt_lib_3dcore.pri \
		../mkspecs/modules/qt_lib_3dcore_private.pri \
		../mkspecs/modules/qt_lib_3dextras.pri \
		../mkspecs/modules/qt_lib_3dextras_private.pri \
		../mkspecs/modules/qt_lib_3dinput.pri \
		../mkspecs/modules/qt_lib_3dinput_private.pri \
		../mkspecs/modules/qt_lib_3dlogic.pri \
		../mkspecs/modules/qt_lib_3dlogic_private.pri \
		../mkspecs/modules/qt_lib_3dquick.pri \
		../mkspecs/modules/qt_lib_3dquick_private.pri \
		../mkspecs/modules/qt_lib_3dquickanimation.pri \
		../mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../mkspecs/modules/qt_lib_3dquickextras.pri \
		../mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../mkspecs/modules/qt_lib_3dquickinput.pri \
		../mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../mkspecs/modules/qt_lib_3dquickrender.pri \
		../mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../mkspecs/modules/qt_lib_3drender.pri \
		../mkspecs/modules/qt_lib_3drender_private.pri \
		../mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../mkspecs/modules/qt_lib_bluetooth.pri \
		../mkspecs/modules/qt_lib_bluetooth_private.pri \
		../mkspecs/modules/qt_lib_bootstrap_private.pri \
		../mkspecs/modules/qt_lib_charts.pri \
		../mkspecs/modules/qt_lib_charts_private.pri \
		../mkspecs/modules/qt_lib_concurrent.pri \
		../mkspecs/modules/qt_lib_concurrent_private.pri \
		../mkspecs/modules/qt_lib_core.pri \
		../mkspecs/modules/qt_lib_core_private.pri \
		../mkspecs/modules/qt_lib_datavisualization.pri \
		../mkspecs/modules/qt_lib_datavisualization_private.pri \
		../mkspecs/modules/qt_lib_dbus.pri \
		../mkspecs/modules/qt_lib_dbus_private.pri \
		../mkspecs/modules/qt_lib_designer.pri \
		../mkspecs/modules/qt_lib_designer_private.pri \
		../mkspecs/modules/qt_lib_designercomponents_private.pri \
		../mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../mkspecs/modules/qt_lib_edid_support_private.pri \
		../mkspecs/modules/qt_lib_egl_support_private.pri \
		../mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../mkspecs/modules/qt_lib_fb_support_private.pri \
		../mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../mkspecs/modules/qt_lib_gamepad.pri \
		../mkspecs/modules/qt_lib_gamepad_private.pri \
		../mkspecs/modules/qt_lib_glx_support_private.pri \
		../mkspecs/modules/qt_lib_gui.pri \
		../mkspecs/modules/qt_lib_gui_private.pri \
		../mkspecs/modules/qt_lib_help.pri \
		../mkspecs/modules/qt_lib_help_private.pri \
		../mkspecs/modules/qt_lib_input_support_private.pri \
		../mkspecs/modules/qt_lib_kms_support_private.pri \
		../mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../mkspecs/modules/qt_lib_location.pri \
		../mkspecs/modules/qt_lib_location_private.pri \
		../mkspecs/modules/qt_lib_multimedia.pri \
		../mkspecs/modules/qt_lib_multimedia_private.pri \
		../mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../mkspecs/modules/qt_lib_multimediawidgets.pri \
		../mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../mkspecs/modules/qt_lib_network.pri \
		../mkspecs/modules/qt_lib_network_private.pri \
		../mkspecs/modules/qt_lib_networkauth.pri \
		../mkspecs/modules/qt_lib_networkauth_private.pri \
		../mkspecs/modules/qt_lib_nfc.pri \
		../mkspecs/modules/qt_lib_nfc_private.pri \
		../mkspecs/modules/qt_lib_opengl.pri \
		../mkspecs/modules/qt_lib_opengl_private.pri \
		../mkspecs/modules/qt_lib_openglextensions.pri \
		../mkspecs/modules/qt_lib_openglextensions_private.pri \
		../mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../mkspecs/modules/qt_lib_positioning.pri \
		../mkspecs/modules/qt_lib_positioning_private.pri \
		../mkspecs/modules/qt_lib_printsupport.pri \
		../mkspecs/modules/qt_lib_printsupport_private.pri \
		../mkspecs/modules/qt_lib_purchasing.pri \
		../mkspecs/modules/qt_lib_purchasing_private.pri \
		../mkspecs/modules/qt_lib_qml.pri \
		../mkspecs/modules/qt_lib_qml_private.pri \
		../mkspecs/modules/qt_lib_qmldebug_private.pri \
		../mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../mkspecs/modules/qt_lib_qmltest.pri \
		../mkspecs/modules/qt_lib_qmltest_private.pri \
		../mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../mkspecs/modules/qt_lib_quick.pri \
		../mkspecs/modules/qt_lib_quick_private.pri \
		../mkspecs/modules/qt_lib_quickcontrols2.pri \
		../mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../mkspecs/modules/qt_lib_quickparticles_private.pri \
		../mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../mkspecs/modules/qt_lib_quickwidgets.pri \
		../mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../mkspecs/modules/qt_lib_remoteobjects.pri \
		../mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../mkspecs/modules/qt_lib_repparser.pri \
		../mkspecs/modules/qt_lib_repparser_private.pri \
		../mkspecs/modules/qt_lib_script.pri \
		../mkspecs/modules/qt_lib_script_private.pri \
		../mkspecs/modules/qt_lib_scripttools.pri \
		../mkspecs/modules/qt_lib_scripttools_private.pri \
		../mkspecs/modules/qt_lib_scxml.pri \
		../mkspecs/modules/qt_lib_scxml_private.pri \
		../mkspecs/modules/qt_lib_sensors.pri \
		../mkspecs/modules/qt_lib_sensors_private.pri \
		../mkspecs/modules/qt_lib_serialbus.pri \
		../mkspecs/modules/qt_lib_serialbus_private.pri \
		../mkspecs/modules/qt_lib_serialport.pri \
		../mkspecs/modules/qt_lib_serialport_private.pri \
		../mkspecs/modules/qt_lib_service_support_private.pri \
		../mkspecs/modules/qt_lib_sql.pri \
		../mkspecs/modules/qt_lib_sql_private.pri \
		../mkspecs/modules/qt_lib_svg.pri \
		../mkspecs/modules/qt_lib_svg_private.pri \
		../mkspecs/modules/qt_lib_testlib.pri \
		../mkspecs/modules/qt_lib_testlib_private.pri \
		../mkspecs/modules/qt_lib_texttospeech.pri \
		../mkspecs/modules/qt_lib_texttospeech_private.pri \
		../mkspecs/modules/qt_lib_theme_support_private.pri \
		../mkspecs/modules/qt_lib_uiplugin.pri \
		../mkspecs/modules/qt_lib_uitools.pri \
		../mkspecs/modules/qt_lib_uitools_private.pri \
		../mkspecs/modules/qt_lib_webchannel.pri \
		../mkspecs/modules/qt_lib_webchannel_private.pri \
		../mkspecs/modules/qt_lib_webengine.pri \
		../mkspecs/modules/qt_lib_webengine_private.pri \
		../mkspecs/modules/qt_lib_webenginecore.pri \
		../mkspecs/modules/qt_lib_webenginecore_private.pri \
		../mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../mkspecs/modules/qt_lib_webenginewidgets.pri \
		../mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../mkspecs/modules/qt_lib_websockets.pri \
		../mkspecs/modules/qt_lib_websockets_private.pri \
		../mkspecs/modules/qt_lib_webview.pri \
		../mkspecs/modules/qt_lib_webview_private.pri \
		../mkspecs/modules/qt_lib_widgets.pri \
		../mkspecs/modules/qt_lib_widgets_private.pri \
		../mkspecs/modules/qt_lib_x11extras.pri \
		../mkspecs/modules/qt_lib_x11extras_private.pri \
		../mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../mkspecs/modules/qt_lib_xml.pri \
		../mkspecs/modules/qt_lib_xml_private.pri \
		../mkspecs/modules/qt_lib_xmlpatterns.pri \
		../mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../mkspecs/features/qt_functions.prf \
		../mkspecs/features/qt_config.prf \
		../mkspecs/linux-g++/qmake.conf \
		../mkspecs/features/spec_post.prf \
		.qmake.stash \
		../mkspecs/features/exclusive_builds.prf \
		../mkspecs/features/toolchain.prf \
		../mkspecs/features/default_pre.prf \
		../mkspecs/features/resolve_config.prf \
		../mkspecs/features/default_post.prf \
		../mkspecs/features/warn_on.prf \
		../mkspecs/features/qt.prf \
		../mkspecs/features/resources.prf \
		../mkspecs/features/moc.prf \
		../mkspecs/features/unix/opengl.prf \
		../mkspecs/features/uic.prf \
		../mkspecs/features/unix/thread.prf \
		../mkspecs/features/qmake_use.prf \
		../mkspecs/features/file_copies.prf \
		../mkspecs/features/testcase_targets.prf \
		../mkspecs/features/exceptions.prf \
		../mkspecs/features/yacc.prf \
		../mkspecs/features/lex.prf \
		atomicSwap.pro backend.h \
		documenthandler.h \
		mustache.h \
		Page.h atomicSwap.cpp \
		backend.cpp \
		documenthandler.cpp \
		mustache.cpp
QMAKE_TARGET  = JimberAtomicSwap
DESTDIR       = 
TARGET        = JimberAtomicSwap


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: atomicSwap.pro ../mkspecs/linux-g++/qmake.conf ../mkspecs/features/spec_pre.prf \
		../mkspecs/common/unix.conf \
		../mkspecs/common/linux.conf \
		../mkspecs/common/sanitize.conf \
		../mkspecs/common/gcc-base.conf \
		../mkspecs/common/gcc-base-unix.conf \
		../mkspecs/common/g++-base.conf \
		../mkspecs/common/g++-unix.conf \
		../mkspecs/qconfig.pri \
		../mkspecs/modules/qt_lib_3danimation.pri \
		../mkspecs/modules/qt_lib_3danimation_private.pri \
		../mkspecs/modules/qt_lib_3dcore.pri \
		../mkspecs/modules/qt_lib_3dcore_private.pri \
		../mkspecs/modules/qt_lib_3dextras.pri \
		../mkspecs/modules/qt_lib_3dextras_private.pri \
		../mkspecs/modules/qt_lib_3dinput.pri \
		../mkspecs/modules/qt_lib_3dinput_private.pri \
		../mkspecs/modules/qt_lib_3dlogic.pri \
		../mkspecs/modules/qt_lib_3dlogic_private.pri \
		../mkspecs/modules/qt_lib_3dquick.pri \
		../mkspecs/modules/qt_lib_3dquick_private.pri \
		../mkspecs/modules/qt_lib_3dquickanimation.pri \
		../mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../mkspecs/modules/qt_lib_3dquickextras.pri \
		../mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../mkspecs/modules/qt_lib_3dquickinput.pri \
		../mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../mkspecs/modules/qt_lib_3dquickrender.pri \
		../mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../mkspecs/modules/qt_lib_3drender.pri \
		../mkspecs/modules/qt_lib_3drender_private.pri \
		../mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../mkspecs/modules/qt_lib_bluetooth.pri \
		../mkspecs/modules/qt_lib_bluetooth_private.pri \
		../mkspecs/modules/qt_lib_bootstrap_private.pri \
		../mkspecs/modules/qt_lib_charts.pri \
		../mkspecs/modules/qt_lib_charts_private.pri \
		../mkspecs/modules/qt_lib_concurrent.pri \
		../mkspecs/modules/qt_lib_concurrent_private.pri \
		../mkspecs/modules/qt_lib_core.pri \
		../mkspecs/modules/qt_lib_core_private.pri \
		../mkspecs/modules/qt_lib_datavisualization.pri \
		../mkspecs/modules/qt_lib_datavisualization_private.pri \
		../mkspecs/modules/qt_lib_dbus.pri \
		../mkspecs/modules/qt_lib_dbus_private.pri \
		../mkspecs/modules/qt_lib_designer.pri \
		../mkspecs/modules/qt_lib_designer_private.pri \
		../mkspecs/modules/qt_lib_designercomponents_private.pri \
		../mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../mkspecs/modules/qt_lib_edid_support_private.pri \
		../mkspecs/modules/qt_lib_egl_support_private.pri \
		../mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../mkspecs/modules/qt_lib_fb_support_private.pri \
		../mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../mkspecs/modules/qt_lib_gamepad.pri \
		../mkspecs/modules/qt_lib_gamepad_private.pri \
		../mkspecs/modules/qt_lib_glx_support_private.pri \
		../mkspecs/modules/qt_lib_gui.pri \
		../mkspecs/modules/qt_lib_gui_private.pri \
		../mkspecs/modules/qt_lib_help.pri \
		../mkspecs/modules/qt_lib_help_private.pri \
		../mkspecs/modules/qt_lib_input_support_private.pri \
		../mkspecs/modules/qt_lib_kms_support_private.pri \
		../mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../mkspecs/modules/qt_lib_location.pri \
		../mkspecs/modules/qt_lib_location_private.pri \
		../mkspecs/modules/qt_lib_multimedia.pri \
		../mkspecs/modules/qt_lib_multimedia_private.pri \
		../mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../mkspecs/modules/qt_lib_multimediawidgets.pri \
		../mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../mkspecs/modules/qt_lib_network.pri \
		../mkspecs/modules/qt_lib_network_private.pri \
		../mkspecs/modules/qt_lib_networkauth.pri \
		../mkspecs/modules/qt_lib_networkauth_private.pri \
		../mkspecs/modules/qt_lib_nfc.pri \
		../mkspecs/modules/qt_lib_nfc_private.pri \
		../mkspecs/modules/qt_lib_opengl.pri \
		../mkspecs/modules/qt_lib_opengl_private.pri \
		../mkspecs/modules/qt_lib_openglextensions.pri \
		../mkspecs/modules/qt_lib_openglextensions_private.pri \
		../mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../mkspecs/modules/qt_lib_positioning.pri \
		../mkspecs/modules/qt_lib_positioning_private.pri \
		../mkspecs/modules/qt_lib_printsupport.pri \
		../mkspecs/modules/qt_lib_printsupport_private.pri \
		../mkspecs/modules/qt_lib_purchasing.pri \
		../mkspecs/modules/qt_lib_purchasing_private.pri \
		../mkspecs/modules/qt_lib_qml.pri \
		../mkspecs/modules/qt_lib_qml_private.pri \
		../mkspecs/modules/qt_lib_qmldebug_private.pri \
		../mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../mkspecs/modules/qt_lib_qmltest.pri \
		../mkspecs/modules/qt_lib_qmltest_private.pri \
		../mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../mkspecs/modules/qt_lib_quick.pri \
		../mkspecs/modules/qt_lib_quick_private.pri \
		../mkspecs/modules/qt_lib_quickcontrols2.pri \
		../mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../mkspecs/modules/qt_lib_quickparticles_private.pri \
		../mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../mkspecs/modules/qt_lib_quickwidgets.pri \
		../mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../mkspecs/modules/qt_lib_remoteobjects.pri \
		../mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../mkspecs/modules/qt_lib_repparser.pri \
		../mkspecs/modules/qt_lib_repparser_private.pri \
		../mkspecs/modules/qt_lib_script.pri \
		../mkspecs/modules/qt_lib_script_private.pri \
		../mkspecs/modules/qt_lib_scripttools.pri \
		../mkspecs/modules/qt_lib_scripttools_private.pri \
		../mkspecs/modules/qt_lib_scxml.pri \
		../mkspecs/modules/qt_lib_scxml_private.pri \
		../mkspecs/modules/qt_lib_sensors.pri \
		../mkspecs/modules/qt_lib_sensors_private.pri \
		../mkspecs/modules/qt_lib_serialbus.pri \
		../mkspecs/modules/qt_lib_serialbus_private.pri \
		../mkspecs/modules/qt_lib_serialport.pri \
		../mkspecs/modules/qt_lib_serialport_private.pri \
		../mkspecs/modules/qt_lib_service_support_private.pri \
		../mkspecs/modules/qt_lib_sql.pri \
		../mkspecs/modules/qt_lib_sql_private.pri \
		../mkspecs/modules/qt_lib_svg.pri \
		../mkspecs/modules/qt_lib_svg_private.pri \
		../mkspecs/modules/qt_lib_testlib.pri \
		../mkspecs/modules/qt_lib_testlib_private.pri \
		../mkspecs/modules/qt_lib_texttospeech.pri \
		../mkspecs/modules/qt_lib_texttospeech_private.pri \
		../mkspecs/modules/qt_lib_theme_support_private.pri \
		../mkspecs/modules/qt_lib_uiplugin.pri \
		../mkspecs/modules/qt_lib_uitools.pri \
		../mkspecs/modules/qt_lib_uitools_private.pri \
		../mkspecs/modules/qt_lib_webchannel.pri \
		../mkspecs/modules/qt_lib_webchannel_private.pri \
		../mkspecs/modules/qt_lib_webengine.pri \
		../mkspecs/modules/qt_lib_webengine_private.pri \
		../mkspecs/modules/qt_lib_webenginecore.pri \
		../mkspecs/modules/qt_lib_webenginecore_private.pri \
		../mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../mkspecs/modules/qt_lib_webenginewidgets.pri \
		../mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../mkspecs/modules/qt_lib_websockets.pri \
		../mkspecs/modules/qt_lib_websockets_private.pri \
		../mkspecs/modules/qt_lib_webview.pri \
		../mkspecs/modules/qt_lib_webview_private.pri \
		../mkspecs/modules/qt_lib_widgets.pri \
		../mkspecs/modules/qt_lib_widgets_private.pri \
		../mkspecs/modules/qt_lib_x11extras.pri \
		../mkspecs/modules/qt_lib_x11extras_private.pri \
		../mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../mkspecs/modules/qt_lib_xml.pri \
		../mkspecs/modules/qt_lib_xml_private.pri \
		../mkspecs/modules/qt_lib_xmlpatterns.pri \
		../mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../mkspecs/features/qt_functions.prf \
		../mkspecs/features/qt_config.prf \
		../mkspecs/linux-g++/qmake.conf \
		../mkspecs/features/spec_post.prf \
		.qmake.stash \
		../mkspecs/features/exclusive_builds.prf \
		../mkspecs/features/toolchain.prf \
		../mkspecs/features/default_pre.prf \
		../mkspecs/features/resolve_config.prf \
		../mkspecs/features/default_post.prf \
		../mkspecs/features/warn_on.prf \
		../mkspecs/features/qt.prf \
		../mkspecs/features/resources.prf \
		../mkspecs/features/moc.prf \
		../mkspecs/features/unix/opengl.prf \
		../mkspecs/features/uic.prf \
		../mkspecs/features/unix/thread.prf \
		../mkspecs/features/qmake_use.prf \
		../mkspecs/features/file_copies.prf \
		../mkspecs/features/testcase_targets.prf \
		../mkspecs/features/exceptions.prf \
		../mkspecs/features/yacc.prf \
		../mkspecs/features/lex.prf \
		atomicSwap.pro \
		atomicSwap.qrc \
		../lib/libQt5QuickControls2.prl \
		../lib/libQt5Quick.prl \
		../lib/libQt5Widgets.prl \
		../lib/libQt5Gui.prl \
		../lib/libQt5Qml.prl \
		../lib/libQt5Network.prl \
		../lib/libQt5Core.prl
	$(QMAKE) -o Makefile atomicSwap.pro
../mkspecs/features/spec_pre.prf:
../mkspecs/common/unix.conf:
../mkspecs/common/linux.conf:
../mkspecs/common/sanitize.conf:
../mkspecs/common/gcc-base.conf:
../mkspecs/common/gcc-base-unix.conf:
../mkspecs/common/g++-base.conf:
../mkspecs/common/g++-unix.conf:
../mkspecs/qconfig.pri:
../mkspecs/modules/qt_lib_3danimation.pri:
../mkspecs/modules/qt_lib_3danimation_private.pri:
../mkspecs/modules/qt_lib_3dcore.pri:
../mkspecs/modules/qt_lib_3dcore_private.pri:
../mkspecs/modules/qt_lib_3dextras.pri:
../mkspecs/modules/qt_lib_3dextras_private.pri:
../mkspecs/modules/qt_lib_3dinput.pri:
../mkspecs/modules/qt_lib_3dinput_private.pri:
../mkspecs/modules/qt_lib_3dlogic.pri:
../mkspecs/modules/qt_lib_3dlogic_private.pri:
../mkspecs/modules/qt_lib_3dquick.pri:
../mkspecs/modules/qt_lib_3dquick_private.pri:
../mkspecs/modules/qt_lib_3dquickanimation.pri:
../mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../mkspecs/modules/qt_lib_3dquickextras.pri:
../mkspecs/modules/qt_lib_3dquickextras_private.pri:
../mkspecs/modules/qt_lib_3dquickinput.pri:
../mkspecs/modules/qt_lib_3dquickinput_private.pri:
../mkspecs/modules/qt_lib_3dquickrender.pri:
../mkspecs/modules/qt_lib_3dquickrender_private.pri:
../mkspecs/modules/qt_lib_3dquickscene2d.pri:
../mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../mkspecs/modules/qt_lib_3drender.pri:
../mkspecs/modules/qt_lib_3drender_private.pri:
../mkspecs/modules/qt_lib_accessibility_support_private.pri:
../mkspecs/modules/qt_lib_bluetooth.pri:
../mkspecs/modules/qt_lib_bluetooth_private.pri:
../mkspecs/modules/qt_lib_bootstrap_private.pri:
../mkspecs/modules/qt_lib_charts.pri:
../mkspecs/modules/qt_lib_charts_private.pri:
../mkspecs/modules/qt_lib_concurrent.pri:
../mkspecs/modules/qt_lib_concurrent_private.pri:
../mkspecs/modules/qt_lib_core.pri:
../mkspecs/modules/qt_lib_core_private.pri:
../mkspecs/modules/qt_lib_datavisualization.pri:
../mkspecs/modules/qt_lib_datavisualization_private.pri:
../mkspecs/modules/qt_lib_dbus.pri:
../mkspecs/modules/qt_lib_dbus_private.pri:
../mkspecs/modules/qt_lib_designer.pri:
../mkspecs/modules/qt_lib_designer_private.pri:
../mkspecs/modules/qt_lib_designercomponents_private.pri:
../mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../mkspecs/modules/qt_lib_edid_support_private.pri:
../mkspecs/modules/qt_lib_egl_support_private.pri:
../mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../mkspecs/modules/qt_lib_fb_support_private.pri:
../mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../mkspecs/modules/qt_lib_gamepad.pri:
../mkspecs/modules/qt_lib_gamepad_private.pri:
../mkspecs/modules/qt_lib_glx_support_private.pri:
../mkspecs/modules/qt_lib_gui.pri:
../mkspecs/modules/qt_lib_gui_private.pri:
../mkspecs/modules/qt_lib_help.pri:
../mkspecs/modules/qt_lib_help_private.pri:
../mkspecs/modules/qt_lib_input_support_private.pri:
../mkspecs/modules/qt_lib_kms_support_private.pri:
../mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../mkspecs/modules/qt_lib_location.pri:
../mkspecs/modules/qt_lib_location_private.pri:
../mkspecs/modules/qt_lib_multimedia.pri:
../mkspecs/modules/qt_lib_multimedia_private.pri:
../mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../mkspecs/modules/qt_lib_multimediawidgets.pri:
../mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../mkspecs/modules/qt_lib_network.pri:
../mkspecs/modules/qt_lib_network_private.pri:
../mkspecs/modules/qt_lib_networkauth.pri:
../mkspecs/modules/qt_lib_networkauth_private.pri:
../mkspecs/modules/qt_lib_nfc.pri:
../mkspecs/modules/qt_lib_nfc_private.pri:
../mkspecs/modules/qt_lib_opengl.pri:
../mkspecs/modules/qt_lib_opengl_private.pri:
../mkspecs/modules/qt_lib_openglextensions.pri:
../mkspecs/modules/qt_lib_openglextensions_private.pri:
../mkspecs/modules/qt_lib_packetprotocol_private.pri:
../mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../mkspecs/modules/qt_lib_positioning.pri:
../mkspecs/modules/qt_lib_positioning_private.pri:
../mkspecs/modules/qt_lib_printsupport.pri:
../mkspecs/modules/qt_lib_printsupport_private.pri:
../mkspecs/modules/qt_lib_purchasing.pri:
../mkspecs/modules/qt_lib_purchasing_private.pri:
../mkspecs/modules/qt_lib_qml.pri:
../mkspecs/modules/qt_lib_qml_private.pri:
../mkspecs/modules/qt_lib_qmldebug_private.pri:
../mkspecs/modules/qt_lib_qmldevtools_private.pri:
../mkspecs/modules/qt_lib_qmltest.pri:
../mkspecs/modules/qt_lib_qmltest_private.pri:
../mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../mkspecs/modules/qt_lib_quick.pri:
../mkspecs/modules/qt_lib_quick_private.pri:
../mkspecs/modules/qt_lib_quickcontrols2.pri:
../mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../mkspecs/modules/qt_lib_quickparticles_private.pri:
../mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../mkspecs/modules/qt_lib_quickwidgets.pri:
../mkspecs/modules/qt_lib_quickwidgets_private.pri:
../mkspecs/modules/qt_lib_remoteobjects.pri:
../mkspecs/modules/qt_lib_remoteobjects_private.pri:
../mkspecs/modules/qt_lib_repparser.pri:
../mkspecs/modules/qt_lib_repparser_private.pri:
../mkspecs/modules/qt_lib_script.pri:
../mkspecs/modules/qt_lib_script_private.pri:
../mkspecs/modules/qt_lib_scripttools.pri:
../mkspecs/modules/qt_lib_scripttools_private.pri:
../mkspecs/modules/qt_lib_scxml.pri:
../mkspecs/modules/qt_lib_scxml_private.pri:
../mkspecs/modules/qt_lib_sensors.pri:
../mkspecs/modules/qt_lib_sensors_private.pri:
../mkspecs/modules/qt_lib_serialbus.pri:
../mkspecs/modules/qt_lib_serialbus_private.pri:
../mkspecs/modules/qt_lib_serialport.pri:
../mkspecs/modules/qt_lib_serialport_private.pri:
../mkspecs/modules/qt_lib_service_support_private.pri:
../mkspecs/modules/qt_lib_sql.pri:
../mkspecs/modules/qt_lib_sql_private.pri:
../mkspecs/modules/qt_lib_svg.pri:
../mkspecs/modules/qt_lib_svg_private.pri:
../mkspecs/modules/qt_lib_testlib.pri:
../mkspecs/modules/qt_lib_testlib_private.pri:
../mkspecs/modules/qt_lib_texttospeech.pri:
../mkspecs/modules/qt_lib_texttospeech_private.pri:
../mkspecs/modules/qt_lib_theme_support_private.pri:
../mkspecs/modules/qt_lib_uiplugin.pri:
../mkspecs/modules/qt_lib_uitools.pri:
../mkspecs/modules/qt_lib_uitools_private.pri:
../mkspecs/modules/qt_lib_webchannel.pri:
../mkspecs/modules/qt_lib_webchannel_private.pri:
../mkspecs/modules/qt_lib_webengine.pri:
../mkspecs/modules/qt_lib_webengine_private.pri:
../mkspecs/modules/qt_lib_webenginecore.pri:
../mkspecs/modules/qt_lib_webenginecore_private.pri:
../mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../mkspecs/modules/qt_lib_webenginewidgets.pri:
../mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../mkspecs/modules/qt_lib_websockets.pri:
../mkspecs/modules/qt_lib_websockets_private.pri:
../mkspecs/modules/qt_lib_webview.pri:
../mkspecs/modules/qt_lib_webview_private.pri:
../mkspecs/modules/qt_lib_widgets.pri:
../mkspecs/modules/qt_lib_widgets_private.pri:
../mkspecs/modules/qt_lib_x11extras.pri:
../mkspecs/modules/qt_lib_x11extras_private.pri:
../mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../mkspecs/modules/qt_lib_xml.pri:
../mkspecs/modules/qt_lib_xml_private.pri:
../mkspecs/modules/qt_lib_xmlpatterns.pri:
../mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../mkspecs/features/qt_functions.prf:
../mkspecs/features/qt_config.prf:
../mkspecs/linux-g++/qmake.conf:
../mkspecs/features/spec_post.prf:
.qmake.stash:
../mkspecs/features/exclusive_builds.prf:
../mkspecs/features/toolchain.prf:
../mkspecs/features/default_pre.prf:
../mkspecs/features/resolve_config.prf:
../mkspecs/features/default_post.prf:
../mkspecs/features/warn_on.prf:
../mkspecs/features/qt.prf:
../mkspecs/features/resources.prf:
../mkspecs/features/moc.prf:
../mkspecs/features/unix/opengl.prf:
../mkspecs/features/uic.prf:
../mkspecs/features/unix/thread.prf:
../mkspecs/features/qmake_use.prf:
../mkspecs/features/file_copies.prf:
../mkspecs/features/testcase_targets.prf:
../mkspecs/features/exceptions.prf:
../mkspecs/features/yacc.prf:
../mkspecs/features/lex.prf:
atomicSwap.pro:
atomicSwap.qrc:
../lib/libQt5QuickControls2.prl:
../lib/libQt5Quick.prl:
../lib/libQt5Widgets.prl:
../lib/libQt5Gui.prl:
../lib/libQt5Qml.prl:
../lib/libQt5Network.prl:
../lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile atomicSwap.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents atomicSwap.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents backend.h documenthandler.h mustache.h Page.h $(DISTDIR)/
	$(COPY_FILE) --parents atomicSwap.cpp backend.cpp documenthandler.cpp mustache.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_atomicSwap.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_atomicSwap.cpp
qrc_atomicSwap.cpp: atomicSwap.qrc \
		../bin/rcc \
		qtquickcontrols2.conf \
		qml/atomicSwap.qml \
		pages/atomicSwap.html \
		pages/ootable/ootable.html
	/home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/rcc -name atomicSwap atomicSwap.qrc -o qrc_atomicSwap.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h ../mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_backend.cpp moc_documenthandler.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_backend.cpp moc_documenthandler.cpp
moc_backend.cpp: ../include/QtCore/QObject \
		../include/QtCore/qobject.h \
		../include/QtCore/qobjectdefs.h \
		../include/QtCore/qnamespace.h \
		../include/QtCore/qglobal.h \
		../include/QtCore/qconfig-bootstrapped.h \
		../include/QtCore/qconfig.h \
		../include/QtCore/qtcore-config.h \
		../include/QtCore/qsystemdetection.h \
		../include/QtCore/qprocessordetection.h \
		../include/QtCore/qcompilerdetection.h \
		../include/QtCore/qtypeinfo.h \
		../include/QtCore/qsysinfo.h \
		../include/QtCore/qlogging.h \
		../include/QtCore/qflags.h \
		../include/QtCore/qatomic.h \
		../include/QtCore/qbasicatomic.h \
		../include/QtCore/qatomic_bootstrap.h \
		../include/QtCore/qgenericatomic.h \
		../include/QtCore/qatomic_cxx11.h \
		../include/QtCore/qatomic_msvc.h \
		../include/QtCore/qglobalstatic.h \
		../include/QtCore/qmutex.h \
		../include/QtCore/qnumeric.h \
		../include/QtCore/qversiontagging.h \
		../include/QtCore/qobjectdefs_impl.h \
		../include/QtCore/qstring.h \
		../include/QtCore/qchar.h \
		../include/QtCore/qbytearray.h \
		../include/QtCore/qrefcount.h \
		../include/QtCore/qarraydata.h \
		../include/QtCore/qstringliteral.h \
		../include/QtCore/qstringalgorithms.h \
		../include/QtCore/qstringview.h \
		../include/QtCore/qstringbuilder.h \
		../include/QtCore/qlist.h \
		../include/QtCore/qalgorithms.h \
		../include/QtCore/qiterator.h \
		../include/QtCore/qhashfunctions.h \
		../include/QtCore/qpair.h \
		../include/QtCore/qbytearraylist.h \
		../include/QtCore/qstringlist.h \
		../include/QtCore/qregexp.h \
		../include/QtCore/qstringmatcher.h \
		../include/QtCore/qcoreevent.h \
		../include/QtCore/qscopedpointer.h \
		../include/QtCore/qmetatype.h \
		../include/QtCore/qvarlengtharray.h \
		../include/QtCore/qcontainerfwd.h \
		../include/QtCore/qobject_impl.h \
		../include/QtQml/QQmlApplicationEngine \
		../include/QtQml/qqmlapplicationengine.h \
		../include/QtQml/qqmlengine.h \
		../include/QtCore/qurl.h \
		../include/QtCore/qurlquery.h \
		../include/QtCore/qshareddata.h \
		../include/QtCore/qhash.h \
		../include/QtCore/qmap.h \
		../include/QtCore/qdebug.h \
		../include/QtCore/qtextstream.h \
		../include/QtCore/qiodevice.h \
		../include/QtCore/qlocale.h \
		../include/QtCore/qvariant.h \
		../include/QtCore/qvector.h \
		../include/QtCore/qpoint.h \
		../include/QtCore/qset.h \
		../include/QtCore/qcontiguouscache.h \
		../include/QtCore/qsharedpointer.h \
		../include/QtCore/qsharedpointer_impl.h \
		../include/QtQml/qjsengine.h \
		../include/QtQml/qjsvalue.h \
		../include/QtQml/qtqmlglobal.h \
		../include/QtQml/qtqml-config.h \
		../include/QtNetwork/qtnetworkglobal.h \
		../include/QtNetwork/qtnetwork-config.h \
		../include/QtQml/qqml.h \
		../include/QtQml/qqmlprivate.h \
		../include/QtQml/qqmlparserstatus.h \
		../include/QtQml/qqmlpropertyvaluesource.h \
		../include/QtQml/qqmllist.h \
		../include/QtCore/qmetaobject.h \
		../include/QtQml/qqmlerror.h \
		../include/QtQml/qqmldebug.h \
		backend.h \
		moc_predefs.h \
		../bin/moc
	/home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/linux-g++ -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/atomicSwap -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtQuickControls2 -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtQuick -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtWidgets -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtGui -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtQml -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtNetwork -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include backend.h -o moc_backend.cpp

moc_documenthandler.cpp: ../include/QtGui/QFont \
		../include/QtGui/qfont.h \
		../include/QtGui/qtguiglobal.h \
		../include/QtCore/qglobal.h \
		../include/QtCore/qconfig-bootstrapped.h \
		../include/QtCore/qconfig.h \
		../include/QtCore/qtcore-config.h \
		../include/QtCore/qsystemdetection.h \
		../include/QtCore/qprocessordetection.h \
		../include/QtCore/qcompilerdetection.h \
		../include/QtCore/qtypeinfo.h \
		../include/QtCore/qsysinfo.h \
		../include/QtCore/qlogging.h \
		../include/QtCore/qflags.h \
		../include/QtCore/qatomic.h \
		../include/QtCore/qbasicatomic.h \
		../include/QtCore/qatomic_bootstrap.h \
		../include/QtCore/qgenericatomic.h \
		../include/QtCore/qatomic_cxx11.h \
		../include/QtCore/qatomic_msvc.h \
		../include/QtCore/qglobalstatic.h \
		../include/QtCore/qmutex.h \
		../include/QtCore/qnumeric.h \
		../include/QtCore/qversiontagging.h \
		../include/QtGui/qtgui-config.h \
		../include/QtGui/qwindowdefs.h \
		../include/QtCore/qobjectdefs.h \
		../include/QtCore/qnamespace.h \
		../include/QtCore/qobjectdefs_impl.h \
		../include/QtGui/qwindowdefs_win.h \
		../include/QtCore/qstring.h \
		../include/QtCore/qchar.h \
		../include/QtCore/qbytearray.h \
		../include/QtCore/qrefcount.h \
		../include/QtCore/qarraydata.h \
		../include/QtCore/qstringliteral.h \
		../include/QtCore/qstringalgorithms.h \
		../include/QtCore/qstringview.h \
		../include/QtCore/qstringbuilder.h \
		../include/QtCore/qsharedpointer.h \
		../include/QtCore/qshareddata.h \
		../include/QtCore/qhash.h \
		../include/QtCore/qiterator.h \
		../include/QtCore/qlist.h \
		../include/QtCore/qalgorithms.h \
		../include/QtCore/qhashfunctions.h \
		../include/QtCore/qpair.h \
		../include/QtCore/qbytearraylist.h \
		../include/QtCore/qstringlist.h \
		../include/QtCore/qregexp.h \
		../include/QtCore/qstringmatcher.h \
		../include/QtCore/qsharedpointer_impl.h \
		../include/QtCore/qobject.h \
		../include/QtCore/qcoreevent.h \
		../include/QtCore/qscopedpointer.h \
		../include/QtCore/qmetatype.h \
		../include/QtCore/qvarlengtharray.h \
		../include/QtCore/qcontainerfwd.h \
		../include/QtCore/qobject_impl.h \
		../include/QtCore/QObject \
		../include/QtGui/QTextCursor \
		../include/QtGui/qtextcursor.h \
		../include/QtGui/qtextformat.h \
		../include/QtGui/qcolor.h \
		../include/QtGui/qrgb.h \
		../include/QtGui/qrgba64.h \
		../include/QtCore/qvector.h \
		../include/QtCore/qpoint.h \
		../include/QtCore/qvariant.h \
		../include/QtCore/qmap.h \
		../include/QtCore/qdebug.h \
		../include/QtCore/qtextstream.h \
		../include/QtCore/qiodevice.h \
		../include/QtCore/qlocale.h \
		../include/QtCore/qset.h \
		../include/QtCore/qcontiguouscache.h \
		../include/QtGui/qpen.h \
		../include/QtGui/qbrush.h \
		../include/QtGui/qmatrix.h \
		../include/QtGui/qpolygon.h \
		../include/QtCore/qrect.h \
		../include/QtCore/qmargins.h \
		../include/QtCore/qsize.h \
		../include/QtGui/qregion.h \
		../include/QtCore/qdatastream.h \
		../include/QtCore/qline.h \
		../include/QtGui/qtransform.h \
		../include/QtGui/qpainterpath.h \
		../include/QtGui/qimage.h \
		../include/QtGui/qpaintdevice.h \
		../include/QtGui/qpixelformat.h \
		../include/QtGui/qpixmap.h \
		../include/QtGui/qtextoption.h \
		../include/QtCore/QUrl \
		../include/QtCore/qurl.h \
		../include/QtCore/qurlquery.h \
		Page.h \
		../include/QtCore/QString \
		mustache.h \
		../include/QtCore/QStack \
		../include/QtCore/qstack.h \
		../include/QtCore/QVariant \
		documenthandler.h \
		moc_predefs.h \
		../bin/moc
	/home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/linux-g++ -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/atomicSwap -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtQuickControls2 -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtQuick -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtWidgets -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtGui -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtQml -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtNetwork -I/home/kristof/Qt5.10.0/5.10.0/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include documenthandler.h -o moc_documenthandler.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

atomicSwap.o: atomicSwap.cpp ../include/QtWidgets/QApplication \
		../include/QtWidgets/qapplication.h \
		../include/QtWidgets/qtwidgetsglobal.h \
		../include/QtGui/qtguiglobal.h \
		../include/QtCore/qglobal.h \
		../include/QtCore/qconfig-bootstrapped.h \
		../include/QtCore/qconfig.h \
		../include/QtCore/qtcore-config.h \
		../include/QtCore/qsystemdetection.h \
		../include/QtCore/qprocessordetection.h \
		../include/QtCore/qcompilerdetection.h \
		../include/QtCore/qtypeinfo.h \
		../include/QtCore/qsysinfo.h \
		../include/QtCore/qlogging.h \
		../include/QtCore/qflags.h \
		../include/QtCore/qatomic.h \
		../include/QtCore/qbasicatomic.h \
		../include/QtCore/qatomic_bootstrap.h \
		../include/QtCore/qgenericatomic.h \
		../include/QtCore/qatomic_cxx11.h \
		../include/QtCore/qatomic_msvc.h \
		../include/QtCore/qglobalstatic.h \
		../include/QtCore/qmutex.h \
		../include/QtCore/qnumeric.h \
		../include/QtCore/qversiontagging.h \
		../include/QtGui/qtgui-config.h \
		../include/QtWidgets/qtwidgets-config.h \
		../include/QtCore/qcoreapplication.h \
		../include/QtCore/qstring.h \
		../include/QtCore/qchar.h \
		../include/QtCore/qbytearray.h \
		../include/QtCore/qrefcount.h \
		../include/QtCore/qnamespace.h \
		../include/QtCore/qarraydata.h \
		../include/QtCore/qstringliteral.h \
		../include/QtCore/qstringalgorithms.h \
		../include/QtCore/qstringview.h \
		../include/QtCore/qstringbuilder.h \
		../include/QtCore/qobject.h \
		../include/QtCore/qobjectdefs.h \
		../include/QtCore/qobjectdefs_impl.h \
		../include/QtCore/qlist.h \
		../include/QtCore/qalgorithms.h \
		../include/QtCore/qiterator.h \
		../include/QtCore/qhashfunctions.h \
		../include/QtCore/qpair.h \
		../include/QtCore/qbytearraylist.h \
		../include/QtCore/qstringlist.h \
		../include/QtCore/qregexp.h \
		../include/QtCore/qstringmatcher.h \
		../include/QtCore/qcoreevent.h \
		../include/QtCore/qscopedpointer.h \
		../include/QtCore/qmetatype.h \
		../include/QtCore/qvarlengtharray.h \
		../include/QtCore/qcontainerfwd.h \
		../include/QtCore/qobject_impl.h \
		../include/QtCore/qeventloop.h \
		../include/QtGui/qwindowdefs.h \
		../include/QtGui/qwindowdefs_win.h \
		../include/QtCore/qpoint.h \
		../include/QtCore/qsize.h \
		../include/QtGui/qcursor.h \
		../include/QtWidgets/qdesktopwidget.h \
		../include/QtWidgets/qwidget.h \
		../include/QtCore/qmargins.h \
		../include/QtGui/qpaintdevice.h \
		../include/QtCore/qrect.h \
		../include/QtGui/qpalette.h \
		../include/QtGui/qcolor.h \
		../include/QtGui/qrgb.h \
		../include/QtGui/qrgba64.h \
		../include/QtGui/qbrush.h \
		../include/QtCore/qvector.h \
		../include/QtGui/qmatrix.h \
		../include/QtGui/qpolygon.h \
		../include/QtGui/qregion.h \
		../include/QtCore/qdatastream.h \
		../include/QtCore/qiodevice.h \
		../include/QtCore/qline.h \
		../include/QtGui/qtransform.h \
		../include/QtGui/qpainterpath.h \
		../include/QtGui/qimage.h \
		../include/QtGui/qpixelformat.h \
		../include/QtGui/qpixmap.h \
		../include/QtCore/qsharedpointer.h \
		../include/QtCore/qshareddata.h \
		../include/QtCore/qhash.h \
		../include/QtCore/qsharedpointer_impl.h \
		../include/QtGui/qfont.h \
		../include/QtGui/qfontmetrics.h \
		../include/QtGui/qfontinfo.h \
		../include/QtWidgets/qsizepolicy.h \
		../include/QtGui/qkeysequence.h \
		../include/QtGui/qevent.h \
		../include/QtCore/qvariant.h \
		../include/QtCore/qmap.h \
		../include/QtCore/qdebug.h \
		../include/QtCore/qtextstream.h \
		../include/QtCore/qlocale.h \
		../include/QtCore/qset.h \
		../include/QtCore/qcontiguouscache.h \
		../include/QtCore/qurl.h \
		../include/QtCore/qurlquery.h \
		../include/QtCore/qfile.h \
		../include/QtCore/qfiledevice.h \
		../include/QtGui/qvector2d.h \
		../include/QtGui/qtouchdevice.h \
		../include/QtGui/qguiapplication.h \
		../include/QtGui/qinputmethod.h \
		../include/QtGui/QGuiApplication \
		../include/QtCore/QDebug \
		../include/QtQml/QQmlApplicationEngine \
		../include/QtQml/qqmlapplicationengine.h \
		../include/QtQml/qqmlengine.h \
		../include/QtQml/qjsengine.h \
		../include/QtQml/qjsvalue.h \
		../include/QtQml/qtqmlglobal.h \
		../include/QtQml/qtqml-config.h \
		../include/QtNetwork/qtnetworkglobal.h \
		../include/QtNetwork/qtnetwork-config.h \
		../include/QtQml/qqml.h \
		../include/QtQml/qqmlprivate.h \
		../include/QtQml/qqmlparserstatus.h \
		../include/QtQml/qqmlpropertyvaluesource.h \
		../include/QtQml/qqmllist.h \
		../include/QtCore/qmetaobject.h \
		../include/QtQml/qqmlerror.h \
		../include/QtQml/qqmldebug.h \
		../include/QtQml/QQmlContext \
		../include/QtQml/qqmlcontext.h \
		../include/QtQml/QQmlFileSelector \
		../include/QtQml/qqmlfileselector.h \
		../include/QtCore/QObject \
		../include/QtCore/QUrl \
		../include/QtQml/QQmlEngine \
		../include/QtQuickControls2/QQuickStyle \
		../include/QtQuickControls2/qquickstyle.h \
		../include/QtQuickControls2/qtquickcontrols2global.h \
		documenthandler.h \
		../include/QtGui/QFont \
		../include/QtGui/QTextCursor \
		../include/QtGui/qtextcursor.h \
		../include/QtGui/qtextformat.h \
		../include/QtGui/qpen.h \
		../include/QtGui/qtextoption.h \
		Page.h \
		../include/QtCore/QString \
		mustache.h \
		../include/QtCore/QStack \
		../include/QtCore/qstack.h \
		../include/QtCore/QVariant \
		../include/QtWebEngine/qtwebengineglobal.h \
		backend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o atomicSwap.o atomicSwap.cpp

backend.o: backend.cpp backend.h \
		../include/QtCore/QObject \
		../include/QtCore/qobject.h \
		../include/QtCore/qobjectdefs.h \
		../include/QtCore/qnamespace.h \
		../include/QtCore/qglobal.h \
		../include/QtCore/qconfig-bootstrapped.h \
		../include/QtCore/qconfig.h \
		../include/QtCore/qtcore-config.h \
		../include/QtCore/qsystemdetection.h \
		../include/QtCore/qprocessordetection.h \
		../include/QtCore/qcompilerdetection.h \
		../include/QtCore/qtypeinfo.h \
		../include/QtCore/qsysinfo.h \
		../include/QtCore/qlogging.h \
		../include/QtCore/qflags.h \
		../include/QtCore/qatomic.h \
		../include/QtCore/qbasicatomic.h \
		../include/QtCore/qatomic_bootstrap.h \
		../include/QtCore/qgenericatomic.h \
		../include/QtCore/qatomic_cxx11.h \
		../include/QtCore/qatomic_msvc.h \
		../include/QtCore/qglobalstatic.h \
		../include/QtCore/qmutex.h \
		../include/QtCore/qnumeric.h \
		../include/QtCore/qversiontagging.h \
		../include/QtCore/qobjectdefs_impl.h \
		../include/QtCore/qstring.h \
		../include/QtCore/qchar.h \
		../include/QtCore/qbytearray.h \
		../include/QtCore/qrefcount.h \
		../include/QtCore/qarraydata.h \
		../include/QtCore/qstringliteral.h \
		../include/QtCore/qstringalgorithms.h \
		../include/QtCore/qstringview.h \
		../include/QtCore/qstringbuilder.h \
		../include/QtCore/qlist.h \
		../include/QtCore/qalgorithms.h \
		../include/QtCore/qiterator.h \
		../include/QtCore/qhashfunctions.h \
		../include/QtCore/qpair.h \
		../include/QtCore/qbytearraylist.h \
		../include/QtCore/qstringlist.h \
		../include/QtCore/qregexp.h \
		../include/QtCore/qstringmatcher.h \
		../include/QtCore/qcoreevent.h \
		../include/QtCore/qscopedpointer.h \
		../include/QtCore/qmetatype.h \
		../include/QtCore/qvarlengtharray.h \
		../include/QtCore/qcontainerfwd.h \
		../include/QtCore/qobject_impl.h \
		../include/QtQml/QQmlApplicationEngine \
		../include/QtQml/qqmlapplicationengine.h \
		../include/QtQml/qqmlengine.h \
		../include/QtCore/qurl.h \
		../include/QtCore/qurlquery.h \
		../include/QtCore/qshareddata.h \
		../include/QtCore/qhash.h \
		../include/QtCore/qmap.h \
		../include/QtCore/qdebug.h \
		../include/QtCore/qtextstream.h \
		../include/QtCore/qiodevice.h \
		../include/QtCore/qlocale.h \
		../include/QtCore/qvariant.h \
		../include/QtCore/qvector.h \
		../include/QtCore/qpoint.h \
		../include/QtCore/qset.h \
		../include/QtCore/qcontiguouscache.h \
		../include/QtCore/qsharedpointer.h \
		../include/QtCore/qsharedpointer_impl.h \
		../include/QtQml/qjsengine.h \
		../include/QtQml/qjsvalue.h \
		../include/QtQml/qtqmlglobal.h \
		../include/QtQml/qtqml-config.h \
		../include/QtNetwork/qtnetworkglobal.h \
		../include/QtNetwork/qtnetwork-config.h \
		../include/QtQml/qqml.h \
		../include/QtQml/qqmlprivate.h \
		../include/QtQml/qqmlparserstatus.h \
		../include/QtQml/qqmlpropertyvaluesource.h \
		../include/QtQml/qqmllist.h \
		../include/QtCore/qmetaobject.h \
		../include/QtQml/qqmlerror.h \
		../include/QtQml/qqmldebug.h \
		documenthandler.h \
		../include/QtGui/QFont \
		../include/QtGui/qfont.h \
		../include/QtGui/qtguiglobal.h \
		../include/QtGui/qtgui-config.h \
		../include/QtGui/qwindowdefs.h \
		../include/QtGui/qwindowdefs_win.h \
		../include/QtGui/QTextCursor \
		../include/QtGui/qtextcursor.h \
		../include/QtGui/qtextformat.h \
		../include/QtGui/qcolor.h \
		../include/QtGui/qrgb.h \
		../include/QtGui/qrgba64.h \
		../include/QtGui/qpen.h \
		../include/QtGui/qbrush.h \
		../include/QtGui/qmatrix.h \
		../include/QtGui/qpolygon.h \
		../include/QtCore/qrect.h \
		../include/QtCore/qmargins.h \
		../include/QtCore/qsize.h \
		../include/QtGui/qregion.h \
		../include/QtCore/qdatastream.h \
		../include/QtCore/qline.h \
		../include/QtGui/qtransform.h \
		../include/QtGui/qpainterpath.h \
		../include/QtGui/qimage.h \
		../include/QtGui/qpaintdevice.h \
		../include/QtGui/qpixelformat.h \
		../include/QtGui/qpixmap.h \
		../include/QtGui/qtextoption.h \
		../include/QtCore/QUrl \
		Page.h \
		../include/QtCore/QString \
		mustache.h \
		../include/QtCore/QStack \
		../include/QtCore/qstack.h \
		../include/QtCore/QVariant \
		../include/QtCore/QDebug \
		ootable.h \
		../include/QtCore/QTextCodec \
		../include/QtCore/qtextcodec.h \
		../include/QtGui/QTextDocument \
		../include/QtGui/qtextdocument.h \
		../include/QtCore/QFile \
		../include/QtCore/qfile.h \
		../include/QtCore/qfiledevice.h \
		../include/QtCore/QFileInfo \
		../include/QtCore/qfileinfo.h \
		../include/QtCore/QFileSelector \
		../include/QtCore/qfileselector.h \
		../include/QtCore/QStringList \
		../include/QtQml/QQmlFile \
		../include/QtQml/qqmlfile.h \
		../include/QtQml/QQmlFileSelector \
		../include/QtQml/qqmlfileselector.h \
		../include/QtQml/QQmlEngine \
		../include/QtQuick/QQuickTextDocument \
		../include/QtQuick/qquicktextdocument.h \
		../include/QtQuick/QQuickItem \
		../include/QtQuick/qquickitem.h \
		../include/QtQuick/qtquickglobal.h \
		../include/QtQuick/qtquick-config.h \
		../include/QtQml/qqmlcomponent.h \
		../include/QtCore/QList \
		../include/QtGui/qevent.h \
		../include/QtGui/qkeysequence.h \
		../include/QtGui/qvector2d.h \
		../include/QtGui/qtouchdevice.h \
		../include/QtGui/qaccessible.h \
		../include/QtCore/qcoreapplication.h \
		../include/QtCore/qeventloop.h \
		../include/QtGui/QTextCharFormat
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backend.o backend.cpp

documenthandler.o: documenthandler.cpp documenthandler.h \
		../include/QtGui/QFont \
		../include/QtGui/qfont.h \
		../include/QtGui/qtguiglobal.h \
		../include/QtCore/qglobal.h \
		../include/QtCore/qconfig-bootstrapped.h \
		../include/QtCore/qconfig.h \
		../include/QtCore/qtcore-config.h \
		../include/QtCore/qsystemdetection.h \
		../include/QtCore/qprocessordetection.h \
		../include/QtCore/qcompilerdetection.h \
		../include/QtCore/qtypeinfo.h \
		../include/QtCore/qsysinfo.h \
		../include/QtCore/qlogging.h \
		../include/QtCore/qflags.h \
		../include/QtCore/qatomic.h \
		../include/QtCore/qbasicatomic.h \
		../include/QtCore/qatomic_bootstrap.h \
		../include/QtCore/qgenericatomic.h \
		../include/QtCore/qatomic_cxx11.h \
		../include/QtCore/qatomic_msvc.h \
		../include/QtCore/qglobalstatic.h \
		../include/QtCore/qmutex.h \
		../include/QtCore/qnumeric.h \
		../include/QtCore/qversiontagging.h \
		../include/QtGui/qtgui-config.h \
		../include/QtGui/qwindowdefs.h \
		../include/QtCore/qobjectdefs.h \
		../include/QtCore/qnamespace.h \
		../include/QtCore/qobjectdefs_impl.h \
		../include/QtGui/qwindowdefs_win.h \
		../include/QtCore/qstring.h \
		../include/QtCore/qchar.h \
		../include/QtCore/qbytearray.h \
		../include/QtCore/qrefcount.h \
		../include/QtCore/qarraydata.h \
		../include/QtCore/qstringliteral.h \
		../include/QtCore/qstringalgorithms.h \
		../include/QtCore/qstringview.h \
		../include/QtCore/qstringbuilder.h \
		../include/QtCore/qsharedpointer.h \
		../include/QtCore/qshareddata.h \
		../include/QtCore/qhash.h \
		../include/QtCore/qiterator.h \
		../include/QtCore/qlist.h \
		../include/QtCore/qalgorithms.h \
		../include/QtCore/qhashfunctions.h \
		../include/QtCore/qpair.h \
		../include/QtCore/qbytearraylist.h \
		../include/QtCore/qstringlist.h \
		../include/QtCore/qregexp.h \
		../include/QtCore/qstringmatcher.h \
		../include/QtCore/qsharedpointer_impl.h \
		../include/QtCore/qobject.h \
		../include/QtCore/qcoreevent.h \
		../include/QtCore/qscopedpointer.h \
		../include/QtCore/qmetatype.h \
		../include/QtCore/qvarlengtharray.h \
		../include/QtCore/qcontainerfwd.h \
		../include/QtCore/qobject_impl.h \
		../include/QtCore/QObject \
		../include/QtGui/QTextCursor \
		../include/QtGui/qtextcursor.h \
		../include/QtGui/qtextformat.h \
		../include/QtGui/qcolor.h \
		../include/QtGui/qrgb.h \
		../include/QtGui/qrgba64.h \
		../include/QtCore/qvector.h \
		../include/QtCore/qpoint.h \
		../include/QtCore/qvariant.h \
		../include/QtCore/qmap.h \
		../include/QtCore/qdebug.h \
		../include/QtCore/qtextstream.h \
		../include/QtCore/qiodevice.h \
		../include/QtCore/qlocale.h \
		../include/QtCore/qset.h \
		../include/QtCore/qcontiguouscache.h \
		../include/QtGui/qpen.h \
		../include/QtGui/qbrush.h \
		../include/QtGui/qmatrix.h \
		../include/QtGui/qpolygon.h \
		../include/QtCore/qrect.h \
		../include/QtCore/qmargins.h \
		../include/QtCore/qsize.h \
		../include/QtGui/qregion.h \
		../include/QtCore/qdatastream.h \
		../include/QtCore/qline.h \
		../include/QtGui/qtransform.h \
		../include/QtGui/qpainterpath.h \
		../include/QtGui/qimage.h \
		../include/QtGui/qpaintdevice.h \
		../include/QtGui/qpixelformat.h \
		../include/QtGui/qpixmap.h \
		../include/QtGui/qtextoption.h \
		../include/QtCore/QUrl \
		../include/QtCore/qurl.h \
		../include/QtCore/qurlquery.h \
		Page.h \
		../include/QtCore/QString \
		mustache.h \
		../include/QtCore/QStack \
		../include/QtCore/qstack.h \
		../include/QtCore/QVariant \
		../include/QtCore/QFile \
		../include/QtCore/qfile.h \
		../include/QtCore/qfiledevice.h \
		../include/QtCore/QFileInfo \
		../include/QtCore/qfileinfo.h \
		../include/QtCore/QFileSelector \
		../include/QtCore/qfileselector.h \
		../include/QtCore/QStringList \
		../include/QtQml/QQmlFile \
		../include/QtQml/qqmlfile.h \
		../include/QtQml/qtqmlglobal.h \
		../include/QtQml/qtqml-config.h \
		../include/QtNetwork/qtnetworkglobal.h \
		../include/QtNetwork/qtnetwork-config.h \
		../include/QtQml/QQmlFileSelector \
		../include/QtQml/qqmlfileselector.h \
		../include/QtQml/QQmlEngine \
		../include/QtQml/qqmlengine.h \
		../include/QtQml/qjsengine.h \
		../include/QtQml/qjsvalue.h \
		../include/QtQml/qqml.h \
		../include/QtQml/qqmlprivate.h \
		../include/QtQml/qqmlparserstatus.h \
		../include/QtQml/qqmlpropertyvaluesource.h \
		../include/QtQml/qqmllist.h \
		../include/QtCore/qmetaobject.h \
		../include/QtQml/qqmlerror.h \
		../include/QtQml/qqmldebug.h \
		../include/QtQuick/QQuickTextDocument \
		../include/QtQuick/qquicktextdocument.h \
		../include/QtGui/QTextDocument \
		../include/QtGui/qtextdocument.h \
		../include/QtQuick/QQuickItem \
		../include/QtQuick/qquickitem.h \
		../include/QtQuick/qtquickglobal.h \
		../include/QtQuick/qtquick-config.h \
		../include/QtQml/qqmlcomponent.h \
		../include/QtCore/QList \
		../include/QtGui/qevent.h \
		../include/QtGui/qkeysequence.h \
		../include/QtGui/qvector2d.h \
		../include/QtGui/qtouchdevice.h \
		../include/QtGui/qaccessible.h \
		../include/QtCore/qcoreapplication.h \
		../include/QtCore/qeventloop.h \
		../include/QtGui/QTextCharFormat \
		../include/QtCore/QTextCodec \
		../include/QtCore/qtextcodec.h \
		../include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o documenthandler.o documenthandler.cpp

mustache.o: mustache.cpp mustache.h \
		../include/QtCore/QStack \
		../include/QtCore/qstack.h \
		../include/QtCore/qvector.h \
		../include/QtCore/qalgorithms.h \
		../include/QtCore/qglobal.h \
		../include/QtCore/qconfig-bootstrapped.h \
		../include/QtCore/qconfig.h \
		../include/QtCore/qtcore-config.h \
		../include/QtCore/qsystemdetection.h \
		../include/QtCore/qprocessordetection.h \
		../include/QtCore/qcompilerdetection.h \
		../include/QtCore/qtypeinfo.h \
		../include/QtCore/qsysinfo.h \
		../include/QtCore/qlogging.h \
		../include/QtCore/qflags.h \
		../include/QtCore/qatomic.h \
		../include/QtCore/qbasicatomic.h \
		../include/QtCore/qatomic_bootstrap.h \
		../include/QtCore/qgenericatomic.h \
		../include/QtCore/qatomic_cxx11.h \
		../include/QtCore/qatomic_msvc.h \
		../include/QtCore/qglobalstatic.h \
		../include/QtCore/qmutex.h \
		../include/QtCore/qnumeric.h \
		../include/QtCore/qversiontagging.h \
		../include/QtCore/qiterator.h \
		../include/QtCore/qlist.h \
		../include/QtCore/qrefcount.h \
		../include/QtCore/qarraydata.h \
		../include/QtCore/qhashfunctions.h \
		../include/QtCore/qstring.h \
		../include/QtCore/qchar.h \
		../include/QtCore/qbytearray.h \
		../include/QtCore/qnamespace.h \
		../include/QtCore/qstringliteral.h \
		../include/QtCore/qstringalgorithms.h \
		../include/QtCore/qstringview.h \
		../include/QtCore/qstringbuilder.h \
		../include/QtCore/qpair.h \
		../include/QtCore/qbytearraylist.h \
		../include/QtCore/qstringlist.h \
		../include/QtCore/qregexp.h \
		../include/QtCore/qstringmatcher.h \
		../include/QtCore/qpoint.h \
		../include/QtCore/QString \
		../include/QtCore/QVariant \
		../include/QtCore/qvariant.h \
		../include/QtCore/qmetatype.h \
		../include/QtCore/qvarlengtharray.h \
		../include/QtCore/qcontainerfwd.h \
		../include/QtCore/qobjectdefs.h \
		../include/QtCore/qobjectdefs_impl.h \
		../include/QtCore/qmap.h \
		../include/QtCore/qdebug.h \
		../include/QtCore/qhash.h \
		../include/QtCore/qtextstream.h \
		../include/QtCore/qiodevice.h \
		../include/QtCore/qobject.h \
		../include/QtCore/qcoreevent.h \
		../include/QtCore/qscopedpointer.h \
		../include/QtCore/qobject_impl.h \
		../include/QtCore/qlocale.h \
		../include/QtCore/qshareddata.h \
		../include/QtCore/qset.h \
		../include/QtCore/qcontiguouscache.h \
		../include/QtCore/qsharedpointer.h \
		../include/QtCore/qsharedpointer_impl.h \
		../include/QtCore/QDebug \
		../include/QtCore/QFile \
		../include/QtCore/qfile.h \
		../include/QtCore/qfiledevice.h \
		../include/QtCore/QStringList \
		../include/QtCore/QTextStream
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mustache.o mustache.cpp

qrc_atomicSwap.o: qrc_atomicSwap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_atomicSwap.o qrc_atomicSwap.cpp

moc_backend.o: moc_backend.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_backend.o moc_backend.cpp

moc_documenthandler.o: moc_documenthandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_documenthandler.o moc_documenthandler.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/kristof/Qt5.10.0/Examples/Qt-5.10.0/quickcontrols2/texteditor || mkdir -p $(INSTALL_ROOT)/home/kristof/Qt5.10.0/Examples/Qt-5.10.0/quickcontrols2/texteditor
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/kristof/Qt5.10.0/Examples/Qt-5.10.0/quickcontrols2/texteditor/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/home/kristof/Qt5.10.0/Examples/Qt-5.10.0/quickcontrols2/texteditor/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/kristof/Qt5.10.0/Examples/Qt-5.10.0/quickcontrols2/texteditor/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/kristof/Qt5.10.0/Examples/Qt-5.10.0/quickcontrols2/texteditor/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

